spring:
  profiles:
    active: developer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  jms:
    template:
      default-destination: 604800000
      receive-timeout: 5000

messaging:
  queues:
    trainerWorkload: trainer-workload-queue
    getTrainerWorkloadRequest: get-trainer-workload-queue-request
    getTrainerWorkloadResponse: get-trainer-workload-queue-response

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

jwt:
  secret: qu8)io1n7%^(*(hhl#k5^&l_kf90!i3o
  lifetime: 60m

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      trainerWorkloadService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000ms

---
spring:
  config:
    activate:
      on-profile: developer

  application:
    name: FinalProjectEpamLabApplication
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:./database/gymdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: test

  application:
    name: FinalProjectEpamLabApplication
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: false
