spring:
  profiles:
    active: developer
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  application:
    name: trainer-workload-service

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

eureka:
  client:
    service-url:
      defaultZone: http://eureka-app:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: developer
  data:
    mongodb:
      uri: mongodb+srv://andriy251101:ECCQvvN6u396x5pi@cluster0.rcc1b.mongodb.net/workloads?retryWrites=true&w=majority
      auto-index-creation: true
      collection-name: trainer_workloads

messaging:
  queues:
    trainerWorkload: trainer-workload-queue
    getTrainerWorkloadRequest: get-trainer-workload-queue-request
    getTrainerWorkloadResponse: get-trainer-workload-queue-response
---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb+srv://andriy251101:ECCQvvN6u396x5pi@cluster0.rcc1b.mongodb.net/test-db?retryWrites=true&w=majority
      auto-index-creation: true
      collection-name: trainer_workloads

messaging:
  queues:
    trainerWorkload: test-trainer-workload-queue
    getTrainerWorkloadRequest: test-get-trainer-workload-queue-request
    getTrainerWorkloadResponse: test-get-trainer-workload-queue-response
---