spring:
  application:
    name: trainer-workload-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  data:
    mongodb:
      uri: mongodb+srv://andriy251101:ECCQvvN6u396x5pi@cluster0.rcc1b.mongodb.net/workloads?retryWrites=true&w=majority
      auto-index-creation: true
      collection-name: trainer_workloads

messaging:
  queues:
    trainerWorkload: trainer-workload-queue
    getTrainerWorkloadRequest: get-trainer-workload-queue-request
    getTrainerWorkloadResponse: get-trainer-workload-queue-response

server:
  port: 8082

jwt:
  secret: qu8)io1n7%^(*(hhl#k5^&l_kf90!i3o
  lifetime: 60m

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html